[config]
schemaVersion = "0.2.1"

[package]
namespace = "Binbin"
name = "Laios_The_Enforcer"
versionNumber = "0.2.2"
description = "New Hero Mod for Laios, the Enforcer. A new Warrior/Healer specialized in Holy, Zeal, and Blunt"
websiteUrl = "https://github.com/binbinmods/Laios"
containsNsfwContent = false

[package.dependencies]
meds-Obeliskial_Essentials = "1.5.1"
meds-Obeliskial_Content = "1.7.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./Laios"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]
